title: Site
pages: default
fields:
  title:
    label: Title
    type:  text
  short_title:
    label: Short title
    type: text
  author:
    label: Author
    type: text
  publisher:
    label: Publisher
    type: text
  publisher-url:
    label: Publisher URL
    type: url
  license:
    label: Licence
    type: text
  license-url:
    label: Licence URL
    type: url
  description:
    label: Description
    type: textarea
  keywords:
    label: Keywords
    type: tags
