files:
  include:
    - 'assets/styles/**/*.scss'
  ignore:
    - 'assets/styles/vendor/**/*.s+(a|c)ss'
options:
  formatter: html
  output-file: 'linters/sass-lint.html'
rules:
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
  extends-before-mixins: 2
  extends-before-declarations: 2
  force-element-nesting: 0
  force-pseudo-nesting: 0
  placeholder-in-extend: 2
  property-sort-order:
    - 1
    -
      order: 'smacss'
  leading-zero: 0
  no-color-literals: 0
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  indentation:
    - 2
    -
      size: 4
